spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true